App\Form\Model\BookDto:
    properties:
        title:
            - NotBlank: ~
        price:
            - NotBlank: ~
        author:
            - NotBlank: ~
        category:
            - NotBlank: ~
    
